version: "3.9"
services:
  consul-server-1:
    image: consul:latest
    container_name: consul-server-1
    ports:
      - "8500:8500"
    volumes:
      - ./data/consul-server-1/:/consul/data:rw
      - ./config/consul-server-1/:/consul/config:rw
    command: ['agent', '-server', '-ui', '-node=consul-server-1', '-bootstrap-expect=1', '-client=0.0.0.0']

  consul-client-1:
    image: consul:latest
    container_name: consul-client-1
    volumes:
      - ./data/consul-client-1/:/consul/data:rw
      - ./config/consul-client-1/:/consul/config:rw
    command: ['agent', '-node=consul-client-1', '-join=consul-server-1']
    depends_on:
      - "consul-server-1"

  consul-client-2:
    image: consul:latest
    container_name: consul-client-2
    volumes:
      - ./data/consul-client-2/:/consul/data:rw
      - ./config/consul-client-2/:/consul/config:rw
    command: ['agent', '-node=consul-client-2', '-join=consul-server-1']
    depends_on:
      - "consul-server-1"

