node_name = "consul-server-2"
server    = true
bootstrap_expect = 3
datacenter = "dc1"
data_dir   = "/consul/data"
log_level  = "INFO"
client_addr = "0.0.0.0"
bind_addr = "{{ GetInterfaceIP \"eth*\" }}"
retry_join = ["consul-server-1", "consul-server-2", "consul-server-3"]
